project_id = "kchblkggcxujyoornmkk"

[functions.process-craving]
verify_jwt = false

[functions.send-reset-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.screen-recipe]
verify_jwt = false

[functions.validate-community]
verify_jwt = false
